# Generated by Django 2.1.5 on 2019-02-10 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=200)),
                ('wins', models.IntegerField(default=0)),
                ('driver_nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f12018.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True)),
                ('driver_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f12018.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_prix_name', models.CharField(max_length=200)),
                ('circuit_name', models.CharField(max_length=200)),
                ('grand_prix_date', models.DateTimeField(verbose_name='Race Date')),
                ('cirtcuit_nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f12018.Country')),
                ('position_driver_race', models.ManyToManyField(to='f12018.Position')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('team_nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f12018.Country')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='race_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f12018.Race'),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_points',
            field=models.ManyToManyField(to='f12018.Position'),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f12018.Team'),
        ),
    ]
