# Generated by Django 2.1.5 on 2019-02-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f12018', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_points',
            field=models.ManyToManyField(blank=True, to='f12018.Position'),
        ),
        migrations.AlterField(
            model_name='race',
            name='position_driver_race',
            field=models.ManyToManyField(blank=True, to='f12018.Position'),
        ),
    ]
