# Generated by Django 2.1.5 on 2019-02-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f12018', '0002_auto_20190210_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='driver_points',
            new_name='driver_race_position',
        ),
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
