# Generated by Django 2.1.5 on 2019-02-13 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f12018', '0003_auto_20190213_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_season_points',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='f12018.Point'),
        ),
    ]
