# Generated by Django 2.1.5 on 2019-02-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f12018', '0004_driver_driver_season_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='points',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
