# Generated by Django 2.1.5 on 2019-02-13 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f12018', '0005_auto_20190213_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_season_points',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f12018.Point'),
        ),
    ]
