# Generated by Django 2.1.5 on 2019-02-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f12018', '0006_auto_20190213_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_season_points',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
