# Generated by Django 2.1.5 on 2019-03-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f12018', '0008_auto_20190309_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='cirtcuit_nationality',
            new_name='circuit_nationality',
        ),
    ]
