# Generated by Django 2.1.5 on 2019-03-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f12018', '0009_auto_20190309_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='driver_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driver_nationality',
            new_name='nationality',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driver_season_points',
            new_name='season_points',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driver_team',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='circuit_nationality',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='grand_prix_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='race',
            name='fastest_lap',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
